---
name: PART3 - CH2 - Artifacts 1
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Create Text
        run: |
          echo "Hello, World!" > sample.txt
      - name: Upload Text
        uses: actions/upload-artifact@v3
        with:
          name: sample
          path: sample.txt
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Download SAMPLE
        uses: actions/download-artifact@v3
        with:
          name: sample
      - name: Print UUID
        run: |
          echo "Artifacts: $(cat sample.txt)"