---
name: PART3 - CH3 - Job with Default
on: workflow_dispatch
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults: # 모든 step에 공통적으로 적용할 구문
      run:
        shell: bash
        working-directory: ./build_sample/python
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - name: Build project
        run: |
          pwd
          echo "Build Project"
      - name: Run tests
        run: |
          pwd
          echo "Run Test"