---
name: Slack Message Bot
on: workflow_dispatch
jobs:
  sendMessage:
    name: SLACK
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack Channel
        id: slack-post
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'github-action-test'
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}